/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-05-28 13:27:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProductDescription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/pages/footer.jsp", Long.valueOf(1495958097751L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en-US\">\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>The Shoe Shop</title>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"./resources/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./resources/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link href=\"./resources/css/Style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"resources/css/footer.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write(" \t<script src= \"http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js\"></script>\r\n");
      out.write(" \t\r\n");
      out.write(" <script>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" var category = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write(" var brandsList = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brandsList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write(" var app = angular.module('myApp', []);\r\n");
      out.write(" app.controller( 'myCtrl', function($scope){\r\n");
      out.write(" \t$scope.category = category;\r\n");
      out.write(" \t$scope.brandsList = brandsList;\r\n");
      out.write("  });\r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write("    \r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body ng-app=\"myApp\">\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"background-color : white;\">\t\t\t<div class=\"col-xs-12 col-sm-2 col-md-2 logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\"><img title=\"TheShoeShop.com\" alt=\"TheShoeShop.com\" src=\"./resources/images/logo.jpg\" class=\"img-responsive\" style=\"width: 170px; height: 100px; \"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-sm-10 col-md-10 header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"h3\"><small>The Smarter Way To Buy</small></p>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("<div class=\"col-xs-12\">\t\t\t\t\t\t\r\n");
      out.write("\t<nav class=\"navbar navbar-light navigation\">\r\n");
      out.write("  \t\t<div class=\"container-fluid\">\r\n");
      out.write("    \t\t<div class=\"navbar-header\">\r\n");
      out.write("      \t\t\t<button type=\"button\" class=\"navbar-toggle buttonlayout\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        \t\t\t<i class=\"fa fa-bars\" style=\"background-color : white;font-size:120%;\"></i>                   \r\n");
      out.write("\t\t      </button>\r\n");
      out.write("     \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"collapse navbar-collapse\" id=\"myNavbar\" ng-controller=\"myCtrl\">\r\n");
      out.write("\t\t\t\t    \t\t\t  <ul class=\"nav navbar-nav main\">\r\n");
      out.write("\t\t\t\t        \t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t          \t\t<a class=\"dropdown-toggle txt\" data-toggle=\"dropdown\" href=\"#\">Men's Section <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t          \t\t<ul class=\"dropdown-menu drop\">\r\n");
      out.write("\t\t\t\t\t\t\t            \t\t<li ng-repeat=\"li in category\"><a href=\"\">{{li.categoryType}}</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t          \r\n");
      out.write("\t\t\t\t\t\t\t\t          </ul>\r\n");
      out.write("\t\t\t\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t          \t\t<a class=\"dropdown-toggle txt\" data-toggle=\"dropdown\" href=\"#\">Women's Section <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t          \t\t<ul class=\"dropdown-menu drop\">\r\n");
      out.write("\t\t\t\t\t\t\t            \t\t<li ng-repeat=\"li in category\"><a href=\"\">{{li.categoryType}}</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t          \r\n");
      out.write("\t\t\t\t\t\t\t\t          </ul>\r\n");
      out.write("\t\t\t\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t      </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t      <ul id=\"signinfeature\" class=\"nav navbar-nav navbar-right main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <li><a href=\"signup\" class=\"txt\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <li><a href=\"login\" class=\"txt\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t      </ul>\r\n");
      out.write("    \t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\" style=\"background: linear-gradient(to top , OliveDrab , white);opacity : 0.8; box-shadow: 0px 1px 2px black;\">\r\n");
      out.write("\t\t<div class=\"col-xs-4 col-xs-offset-4\"  style=\"background-color : whitesmoke ;height: 20px;box-shadow: 0px 1px 2px black;\">\r\n");
      out.write("\t\t<hr style=\"margin-top: 10px; border-top: 1px solid OliveDrab;\">\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"input-group searchbox\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Search for Products & Brands\" class=\"form-control\" name=\"in\">\r\n");
      out.write("\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-search\"></i></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron\" style=\"margin-top : 30px;margin-bottom :0;\">\r\n");
      out.write("\t\t<hr style=\"margin-top: -15px;margin-bottom: 5px; border-top: 1px solid OliveDrab;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t<pre>\r\n");
      out.write("\t   &copy;2017 TheShoeShop.com    \r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Keep In Touch  <a href=\"http://www.facebook.com\" id=\"fb\"><i class=\"fa fa-facebook-official\"></i></a>  <a href=\"http://www.youtube.com\" id=\"yt\"><i class=\"fa fa-youtube-play\"></i></a>  <a href=\"http://www.twitter.com\" id=\"tw\"><i class=\"fa fa-twitter\"></i></a>  <a href=\"http://www.google.co.in\" id=\"gp\"><i class=\"fa fa-google-plus-square\"></i></a>\r\n");
      out.write("\t</pre>  \r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span>&nbsp;&nbsp;THE SHOE SHOP</span>\r\n");
      out.write("\t\t\t\t\t<ul class=\"summary\" style=\"list-style-type : none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"aboutUs\">About Us&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Contact Us&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">FAQ&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span>&nbsp;&nbsp;TOP SELLING BRANDS</span>\r\n");
      out.write("\t\t\t\t\t<ul class=\"summary\" style=\"list-style-type: none;\" ng-controller=\"myCtrl\">\r\n");
      out.write("\t\t\t\t\t\t<li ng-repeat=\"li in brandsList\"><a href=\"#\">{{li}}&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span>&nbsp;&nbsp;HELP</span>\r\n");
      out.write("\t\t\t\t\t<ul class=\"summary\" style=\"list-style-type: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Payments&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Shipping&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Cancellation & Returns&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Track Order&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<hr style=\" border-top : 1px solid white ;width : 90%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"footerlogo\" id=\"hide\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/logo.jpg\" width=\"154\" height=\"120\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/footer7.jpg\" width=\"154\" height=\"120\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/footer6.jpg\" width=\"154\" height=\"120\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/footer4.jpg\" width=\"154\" height=\"120\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/footer5.jpg\" width=\"154\" height=\"120\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/footer2.jpg\" width=\"154\" height=\"120\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/footer1.jpg\" width=\"154\" height=\"120\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
